" 修改leader键
let mapleader = "\<space>"
let g:mapleader ="\<space>"
		" ii 替换 Esc
inoremap ii <Esc>
		" 将 ; 绑定到 : 用于快速进入命令行
nnoremap ; :

" ##### 插件配置
if filereadable(expand("~/.vimrc.bundles"))
  source ~/.vimrc.bundles
endif


" ##### 基本配置
if filereadable(expand("~/.vimrc.config_base"))
  source ~/.vimrc.config_base
endif


" #####  文件类型设置
if filereadable(expand("~/.vimrc.config_filetype"))
  source ~/.vimrc.config_filetype
endif

" ##### 本地自定义配置
if filereadable(expand("~/.vimrc.local"))
    source ~/.vimrc.local
endif

" ##### 各种 vim 文件设置
" 备份
set backup
set backupdir=~/.vim/vimbackup

" 交换文件
set swapfile
set dir=~/.vim/vimswap

" undo
if has('persistent_undo')
  set undolevels=1000         " How many undos
  set undoreload=10000        " number of lines to save for undo
  set undofile                " So is persistent undo ...
  set undodir=~/.vim/vimundo/
endif
