#!/bin/bash
# ====================================================
#   Copyright (C)2015 All rights reserved.
#
#   Author  : bbxytl
#   Email   : bbxytl@gmail.com
#   FileName: config
#   LastModify : 2015-07-20 14:45
#   Describe:
#
#   Log     :
#
# ====================================================

# 安装环境

BASEDIR=$(dirname $0)
cd $BASEDIR
CURRENT_DIR=`pwd`


if [ $# -ge 1 ];then
	PASSWD=$1
else
	echo " 安装环境，过程中需要输入密码。。。。。请输入："
	read PASSWD
fi

today=`date +%Y%m%d`
cd $HOME
if [ ! -e $HOME/mydotfiles ];then mkdir $HOME/mydotfiles;else mkdir $HOME/mydotfiles.$today;fi
mv $CURRENT_DIR $HOME/mydotfiles/b-dotfiles
PACKGES=$HOME/mydotfiles/packges
if [ ! -e $PACKGES ];then mkdir $PACKGES;else mkdir $PACKGES.$today;fi
CURRENT_DIR="$HOME/mydotfiles/b-dotfiles"
cd $CURRENT_DIR

tmp="$HOME/mydotfiles/tmp"
if [ ! -e $tmp ];then mkdir $tmp; fi

system_shell=$SHELLL
export SHELL="/bin/sh"

echo $PASSWD | sudo -S yum install -y python-devel.x86_64
sudo yum groupinstall 'Development Tools'
sudo rpm -Uvh http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
echo $PASSWD | sudo -S yum install -y  the_silver_searcher


echo " wget install......"
echo $PASSWD | sudo -S yum install -y  wget
echo " pip install......."
rpm -iUvh http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
echo $PASSWD | sudo -S yum install -y  epel-release
echo $PASSWD | sudo -S yum install -y  python-pip
echo " tmux env install........"
echo $PASSWD | sudo -S yum install -y  ncurses-devel
echo $PASSWD | sudo -S yum install -y  autoconf m4 perl automake
sudo autoconf -ivf

echo $PASSWD | sudo -S  pip install pyflakes
echo $PASSWD | sudo -S  pip install pylint
echo $PASSWD | sudo -S  pip install pep8
pep8str="[pep8]\nmax-line-length = 120"
if [ ! -e $HOME/.config ]; then mkdir $HOME/.config; fi
if [ ! -e $HOME/.config/pep8 ];then
	echo -e pep8str > $HOME/.config/pep8
fi

# 安装 locate 查找包
echo $PASSWD | sudo -S  yum -y install mlocate.x86_64
echo $PASSWD | sudo -S  updatedb

# 安装 CMake 命令
installfg=true
if locate *cmake*3*2*>/dev/null 2>&1 ;then installfg=false;fi
if $installfg;then
    if [ ! -e $tmp ];then mkdir $tmp ; fi
    cd $tmp
    wget http://www.cmake.org/files/v3.2/cmake-3.2.3.tar.gz
    tar -zxvf cmake-3.2.3.tar.gz
    cd cmake-3.2.3
    ./bootstrap
    make && echo $PASSWD | sudo -S make install
    cd $CURRENT_DIR
fi

echo $PASSWD | sudo -S yum install ctags

# 更新vim为 7.4
installfg=true
if locate *cmake*3*2*>/dev/null 2>&1 ;then installfg=false;fi
if $installfg;then
    if [ ! -e $tmp ];then mkdir $tmp ; fi
    cd $tmp
	wget ftp://ftp.vim.org/pub/vim/unix/vim-7.4.tar.bz2
	tar -xjf vim-7.4.tar.bz2
	cd vim74
	make && echo $PASSWD | sudo -S make install
    cd $CURRENT_DIR
fi

export SHELL=$system_shell
