# .bash_profile


if [ -f ~/.bashrc ];then
    . ~/.bashrc
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

[[ -s "/Users/long/.gvm/scripts/gvm" ]] && source "/Users/long/.gvm/scripts/gvm"
