# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
export TERM=xterm-256color
## Uncomment the following line if you don't like systemctl's auto-paging feature:
## export SYSTEMD_PAGER=
export PS1='\e[0;31m\u@\h \w\$ \e[m'
## User specific aliases and functions
#
if [ -f ~/.bashrc.local ];then
	source ~/.bashrc.local
fi

if [ -f ~/.bash_profile ];then
	source ~/.bash_profile
fi

if [ -f ~/.alias.sh ]; then
	source ~/.alias.sh
fi

zsh
